version: "3"

services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - mern-app
    stdin_open: true
    tty: true
  
  backend:
    image: backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mern-app
  
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  
networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local